#本地环境
spring:
  data:
    mongodb:
      uri: mongodb://username:password@localhost:27017/coin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/coin?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: coin
    password: xxxx
    filters: wall,mergeStat
    data-source-name: gunsdb
  redis:  ###### redis 配置
    host: 127.0.0.1  # ip地址
    database: 0 # redis数据库  0-15
    port: 6379  # 端口号
    password: xxxx # 无密码不填 hjx729299893
    timeout: 30000s   # 连接超时时间 （默认1天）
    lettuce:
      shutdown-timeout: 100ms # 关闭超时时间 默认 100ms
      pool: # lettuce 连接池
        max-active: -1 # 连接池最大连接数 默认 8（-1 ：表示没有限制）
        max-wait: 60000ms # 连接池最大阻塞等待时间 默认-1ms （-1 :表示没有限制） 这里设置1分钟
        max-idle: 100 # 最大空闲连接  默认 8
        min-idle: 0 # 最小空闲连接  默认

#系统安全码
system:
  security:
    code: 123456
#多数据源情况的配置
guns:
  muti-datasource:
    open: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=America/New_York
    username: db
    password: db
    data-source-name: otherdb
# h5注册页信息
h5:
  url: https://webx8.meitba.com #地址
  prefix: /modular/com/h5_reg/ #文件前缀
  reg: xmex.html
  agree: xmexAgree.html
  link: exitLink.html
  regApi: /api/visitor/reg/ #邀请注册
  agreeApi: /api/visitor/reg/agree # 用户协议
  zhengCeApi: /api/visitor/reg/zhengce
  linkApi: /api/visitor/reg/link  # 下载链接


#钱包配置,弃用
eth:
  key: 111
  secret: 111
  memberCode: 1111
  #创建钱包地址
  createUrl: http://1.1.11.111:8186/coinWeb/createNewAccount
  #提幣地址
  mentionUrl: http://1.1.11.111:8186/coinWeb/sendTransaction
  #地址校验
  checkAddressUrl: http://1.1.11.11:8186/coinWeb/validateAddress
  #查询公账账户余额
  accountBalanceUrl: http://1.1.1.11:8186/coinWeb/getBalance
  #公账提币交易
  sendPublicTransaction: http://1.1.46.1:8186/coinWeb/sendPublicTransaction
  #查询主账户地址
  findMainAccount: http://1.1.11.1:8186/coinWeb/findMainAccount
ida:
  appid: test
  key: test
  # 测试环境 当前为正式
  url: https://test/paygateway/toCashierIndex
  #
  pickupUrl: http://127.0.0.1/
  receiveUrl: http://127.0.0.1/api/personal/legalCallback


dromara:
  x-file-storage: #文件存储配置
    default-platform: local-plus-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    local-plus:
      - platform: local-plus-1 # 存储平台标识
        enable-storage: true  #启用存储
        enable-access: false #启用访问（线上请使用 Nginx 配置，效率更高）
        domain: https://img.cointrade.com # 访问域名，例如：“http://127.0.0.1:8030/file/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        base-path: / # 基础路径
        # path-patterns: /file/** # 访问路径
        storage-path: /www/wwwroot/img.cointrade.com # 存储路径


# 充值提币配置
bipay:
  gateway: https://sig10.udun.io      # 网关
  merchantId: 316224                  # 商户id
  merchantKey: xxx # 商户密钥
  callbackUrl: https://api.xxxx.com/api/common/bipay/notify

# Sinohope配置
waas:
  publicKey: xxx
  privateKey: xxxxxxxxxxx
  vaultId: xxxxxxxxxxx
  website: xxxxxxxxxxx