let arr = [
    {
        name:'BTC/USDT',
        logo:'https://static.coinall.ltd/cdn/oksupport/asset/currency/icon/btc.png?x-oss-process=image/format,webp'
    },
    {
        name:'ETH/USDT',
        logo:'https://cdn.mytoken.org/FvKK2xxE7DNqbKHA9Dle2FPheJJe'//logo后面就是对应的币种的图片地址
    },
    {
        name:'EOS/USDT',
        logo:'https://cdn.mytoken.org/FjMXTFsqGTqS3rNEygtKl6BeBJeY'
    },
    {
        name:'BCH/USDT',
        logo:'https://cdn.mytoken.org/FnZQXaBg1O881ZLdgtED8BWuNWNg'
    },
    {
        name:'LTC/USDT',
        logo:'https://cdn.mytoken.org/FsV55Vw-MbneC3kELoo2eQ3w80il'
    },
    {
        name:'ETC/USDT',
        logo:'https://cdn.mytoken.org/Fg1hRpilNVpaBYCBv6cyVRM0Xo7k'
    },
    {
        name:'XRP/USDT',
        logo:'https://cdn.mytoken.org/FkksO-h3G5SYKSxonpte1S3LYPcR'
    },
    {
        name:'BSV/USDT',
        logo:'https://cdn.mytoken.org/FhVog9brdyHpHtYbKgDZW2Pygh-j'
    },
    {
        name:'FIL/USDT',
        logo:'https://cdn.mytoken.org/586fd5f2933e2e03f08b52d3d488a19a'
    },
    {
        name:'ADA/USDT',
        logo:'https://cdn.mytoken.org/e7f4b8f7f40dd261a2d566fe00d96a27'
    },
    {
        name:'ICP/USDT',
        logo:'https://cdn.mytoken.org/FqxpOkn2ub-3xSPbvP2PGMNlZbCd'
    },
    {
        name:'DOT/USDT',
        logo:'https://cdn.mytoken.org/FmqohnjP-h3SJa7Bxufh8yHQNDI9'
    },
    {
        name:'UNI/USDT',
        logo:'https://cdn.mytoken.org/FoniGRgNwGliTcs8QY_mcVy2E6FX'
    },
    { 
        name:'UNI/USDT',
        logo:'https://cdn.mytoken.org/FoniGRgNwGliTcs8QY_mcVy2E6FX'
    },
    { 
        name:'SOL/USDT',
        logo:'https://cdn.mytoken.org/Fo0XfgiUk-ZIJ1OtZ_Py4qihCIOg'
    },

    { 
        name:'VET/USDT',
        logo:'https://cdn.mytoken.org/Fn46gvw7N27NhjNrNu5iTH4Jlfsc'
    },
    { 
        name:'TRX/USDT',
        logo:'https://cdn.mytoken.org/Ft9hwnVt1zwnE_y5862FZtss2sl2'
    },
    { 
        name:'XMR/USDT',
        logo:'https://cdn.mytoken.org/a654ceec9011a417d48ec2388f0c2e6f'
    },
    { 
        name:'DAI/USDT',
        logo:'https://cdn.mytoken.org/Flvq0lM_HJDxgZLJs6Gt_UmVo0r8'
    },
    { 
        name:'CRO/USDT',
        logo:'https://cdn.mytoken.org/FkynWHLha35pCU_HhjONFtmYGH7h'
    },
    { 
        name:'FTT/USDT',
        logo:'https://cdn.mytoken.org/FoWMrRQMJHwZuY0qmh-FwGWFmsxm'
    },
    { 
        name:'MKR/USDT',
        logo:'https://cdn.mytoken.org/FtVGPotPRpKxMIddVuoqmFFT1AAA'
    },
    { 
        name:'XTZ/USDT',
        logo:'https://cdn.mytoken.org/FiduE3ewz8IMTIRrxiT92SGWT3tJ'
    },
    { 
        name:'NEO/USDT',
        logo:'https://cdn.mytoken.org/FvfT8zLr_MTak5DiA8PmNoUSDias'
    },
    { 
        name:'GRT/USDT',
        logo:'https://cdn.mytoken.org/FlXMa1eEtIrgpZo2n2AHAx4vTqqh'
    },
    { 
        name:'HT/USDT',
        logo:'https://cdn.mytoken.org/FnjjYhzTi48HXz8t7BdHyKM2i5Cn'
    },
    { 
        name:'KSM/USDT',
        logo:'https://cdn.mytoken.org/FsoKgx4ZBuRCK43CGVjFNWY4Z7-j'
    },
    { 
        name:'BTT/USDT',
        logo:'https://cdn.mytoken.org/FmBjAu0gh_L8itrobPVb5cooXnC9'
    },
    { 
        name:'CHZ/USDT',
        logo:'https://cdn.mytoken.org/Ftic3JdfaP2g6VWgxRs1fUR5tTo2'
    },
    { 
        name:'DCR/USDT',
        logo:'https://cdn.mytoken.org/Fm84uYvRLP6d_nlEGJ6GCc9BUtkh'
    },
    { 
        name:'AXS/USDT',
        logo:'https://cdn.mytoken.org/FoRz7x35ttgwW3VmpBjsxjxkTOTl'
    },
    { 
        name:'ZEC/USDT',
        logo:'https://cdn.mytoken.org/a9495f21ae34a6741d0fd3c86e86c760'
    },
    { 
        name:'SNX/USDT',
        logo:'https://cdn.mytoken.org/FvVzjjCytEsag7j04ldIds9lLiE2'
    },
    { 
        name:'ENJ/USDT',
        logo:'https://cdn.mytoken.org/enjin-coin.png'
    },
    { 
        name:'YFI/USDT',
        logo:'https://cdn.mytoken.org/Fn-vTE5fEtZ1LhCnnM3ta-eHxd3e'
    },
    { 
        name:'XEM/USDT',
        logo:'https://cdn.mytoken.org/006c5e2eef5bf0b124c161572ba1a940'
    },
    { 
        name:'PAX/USDT',
        logo:'https://cdn.mytoken.org/Frr7C-GfIhtf51XOB8K8BIKeWXHQ'
    },
    { 
        name:'MDX/USDT',
        logo:'https://cdn.mytoken.org/FgVBmITbPswct-fdteS0VXAJFR7A'
    },
    { 
        name:'ZIL/USDT',
        logo:'https://cdn.mytoken.org/FkyROESe5wy9rAw_tYUsyCCeiNID'
    },
    { 
        name:'AT/USDT',
        logo:'https://cdn.mytoken.org/FlZsq3hn_B-Tob0aL0Ia9Jt9Y8ce'
    },
    { 
        name:'XLM/USDT',
        logo:'https://cdn.mytoken.org/Fuz_J0Kq9qLFGwc_4OJlnJq17QWO'
    },
    { 
        name:'XLM/USDT',
        logo:'https://cdn.mytoken.org/Fuz_J0Kq9qLFGwc_4OJlnJq17QWO'
    },
    { 
        name:'XEC/USDT',
        logo:'https://cdn.mytoken.org/FkSLgW_L2sbS8h4VAg-3rRHIrhoO'
    },
    { 
        name:'ZIL/USDT',
        logo:'https://cdn.mytoken.org/FkyROESe5wy9rAw_tYUsyCCeiNID'
    },
    { 
        name:'BAT/USDT',
        logo:'https://cdn.mytoken.org/ea9f325c96f97a6ba5ad9ae765f5e35a'
    },
    { 
        name:'BNT/USDT',
        logo:'https://cdn.mytoken.org/Fk9vkaj9TvOBGbQTk0MtJOSuytzs'
    },
    { 
        name:'PAX/USDT',
        logo:'https://cdn.mytoken.org/Frr7C-GfIhtf51XOB8K8BIKeWXHQ'
    },
    { 
        name:'RVN/USDT',
        logo:'https://cdn.mytoken.org/e0bf1a3c0a0593d6ed00454a83d755f1'
    },
    { 
        name:'ONT/USDT',
        logo:'https://cdn.mytoken.org/FoNhuguKlAIR-66-v_OZDw6Fm9Hb'
    },
    { 
        name:'ONE/USDT',
        logo:'https://cdn.mytoken.org/FvaJTw6di71vnWBunMzHTdajg6H3'
    },
    { 
        name:'ZRX/USDT',
        logo:'https://cdn.mytoken.org/ce5a2273226f59877566b71b5d8e837a'
    },
    { 
        name:'ZZEN/USDT',
        logo:'https://cdn.mytoken.org/Fkg6tebTDviK-jU_f5MRUbZSYns1'
    },
    { 
        name:'ICX/USDT',
        logo:'https://cdn.mytoken.org/FlICEhVLPpIwPNDd8Hi_PA4XHEKu'
    },
    { 
        name:'CRV/USDT',
        logo:'https://cdn.mytoken.org/FtXB1bIxROD8jAeiDv6hJIuqtQu6'
    },
    { 
        name:'KNC/USDT',
        logo:'https://cdn.mytoken.org/FraTeu8s0jBbpeZVY5RBvUMj5rG_'
    },
    { 
        name:'XCH/USDT',
        logo:'https://cdn.mytoken.org/FuaOgxlgqq3KCCfm7mnVe3-xxaM4'
    },
    { 
        name:'HBC/USDT',
        logo:'https://cdn.mytoken.org/FuBvcDC7h3qPFKqF5rFkKCT0VkOb'
    },
    { 
        name:'OGN/USDT',
        logo:'https://cdn.mytoken.org/FmJjjgRDoN0OihJ1CbuQFQiSNpni'
    },
    { 
        name:'OXT/USDT',
        logo:'https://cdn.mytoken.org/FmlBxYc8gzf_kUJcgAcdzLTGrvu3'
    },
    { 
        name:'DFA/USDT',
        logo:'https://cdn.mytoken.org/FpRU7QRptBFVZ-pXtWDAPD8gkhqy'
    },
    { 
        name:'CVC/USDT',
        logo:'https://cdn.mytoken.org/civic.png'
    },
    { 
        name:'ZKS/USDT',
        logo:'https://cdn.mytoken.org/FpMvapjpzKAMvzSwr87tFjTgMIsp'
    },
    { 
        name:'BTS/USDT',
        logo:'https://cdn.mytoken.org/Fo5Syh3cIHTRHQ9uRcPMbcBtVZ-P'
    },
    { 
        name:'ELF/USDT',
        logo:'https://cdn.mytoken.org/586fd5f2933e2e03f08b52d3d488a19a'
    },
    { 
        name:'CHR/USDT',
        logo:'https://cdn.mytoken.org/FlZsq3hn_B-Tob0aL0Ia9Jt9Y8ce'
    },
    { 
        name:'UTK/USDT',
        logo:'https://cdn.mytoken.org/FtPXbzLDWF9VYSjl5qCeYk09SSZu'
    },
    { 
        name:'CRU/USDT',
        logo:'https://cdn.mytoken.org/FugcfvYEf7EC3bxqCe2LthsUK-iA'
    },
    { 
        name:'CRE/USDT',
        logo:'https://cdn.mytoken.org/FkFqRMMc-FuOshQOmFYeWITKsG3V'
    },
    { 
        name:'TRB/USDT',
        logo:'https://cdn.mytoken.org/Fk7JM95ZdBS95a-vgPB2-jsnUGlS'
    },
    { 
        name:'MXC/USDT',
        logo:'https://cdn.mytoken.org/FgFQcG-XJmEJh0bT8VQifbEJsbnB'
    },
    { 
        name:'KAN/USDT',
        logo:'https://cdn.mytoken.org/FhqRkGjjaYkGw4RcLLNQ9Q8NuPE1'
    },
    { 
        name:'GXC/USDT',
        logo:'https://cdn.mytoken.org/FnwhAallYVydGgT_chu_88RHV86N'
    },
    { 
        name:'NBS/USDT',
        logo:'https://cdn.mytoken.org/FtQPrcPll90pxWIW12fAZ3eeZuQp'
    },
    { 
        name:'PAI/USDT',
        logo:'https://cdn.mytoken.org/FruuNLtPZPkdAyannTTNCri46RoI'
    },
    { 
        name:'AST/USDT',
        logo:'https://cdn.mytoken.org/FgYjkwXYsqlaX2qwy0bqpWctvUdb'
    },

    { 
        name:'WTC/USDT',
        logo:'https://cdn.mytoken.org/b3f4b9df4031a928e66a8728d62a4128'
    },

    { 
        name:'DOGE/USDT',
        logo:'https://cdn.mytoken.org/Fo0AJ16ueLMz5Zd3Fh0WfkGj2870'
    },






];
export default arr;