#本地环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/coin?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: coin
    password: xxxx
    filters: wall,mergeStat
    data-source-name: gunsdb
  redis:  ###### redis 配置
    host: 127.0.0.1  # ip地址
    database: 0  # redis数据库  0-15
    port: 6379  # 端口号
    password: redis-123 # 无密码不填 hjx729299893
    timeout: 30000s   # 连接超时时间 （默认1天）
    lettuce:
      shutdown-timeout: 100ms # 关闭超时时间 默认 100ms
      pool: # lettuce 连接池
        max-active: 8 # 连接池最大连接数 默认 8（-1 ：表示没有限制）
        max-wait: 60000ms # 连接池最大阻塞等待时间 默认-1ms （-1 :表示没有限制） 这里设置1分钟
        max-idle: 8 # 最大空闲连接  默认 8
        min-idle: 0 # 最小空闲连接  默认

#系统安全码
system:
  security:
    code: 123456
#多数据源情况的配置
guns:
  muti-datasource:
    open: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: db
    password: db
    data-source-name: otherdb
# h5注册页信息
h5:
  url: https://webx8.meitba.com #地址
  prefix: /modular/com/h5_reg/ #文件前缀
  reg: xmex.html
  agree: xmexAgree.html
  link: exitLink.html
  regApi: /api/visitor/reg/ #邀请注册
  agreeApi: /api/visitor/reg/agree # 用户协议
  zhengCeApi: /api/visitor/reg/zhengce
  linkApi: /api/visitor/reg/link  # 下载链接


#钱包配置
eth:
  key: 111
  secret: 111
  memberCode: 1111
  #创建钱包地址
  createUrl: http://1.1.11.111:8186/coinWeb/createNewAccount
  #提幣地址
  mentionUrl: http://1.1.11.111:8186/coinWeb/sendTransaction
  #地址校验
  checkAddressUrl: http://1.1.11.11:8186/coinWeb/validateAddress
  #查询公账账户余额
  accountBalanceUrl: http://1.1.1.11:8186/coinWeb/getBalance
  #公账提币交易
  sendPublicTransaction: http://1.1.46.1:8186/coinWeb/sendPublicTransaction
  #查询主账户地址
  findMainAccount: http://1.1.11.1:8186/coinWeb/findMainAccount
ida:
  appid: test
  key: test
  # 测试环境 当前为正式
  url: https://test/paygateway/toCashierIndex
  #
  pickupUrl: http://127.0.0.1/
  receiveUrl: http://127.0.0.1/api/personal/legalCallback
